# Generated by Django 3.0.8 on 2020-07-27 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('middlename', models.CharField(max_length=200)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('homeaddress', models.TextField()),
                ('homeownership', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('businessname', models.CharField(max_length=200)),
                ('specialtypractice', models.CharField(max_length=200)),
                ('tenurepractice', models.CharField(max_length=200)),
                ('prcno', models.CharField(max_length=200)),
                ('businessaddress', models.TextField()),
                ('businessphone', models.CharField(max_length=200)),
                ('businessemail', models.CharField(max_length=200)),
                ('contactperson', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('contactpersonphone', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
