# Generated by Django 3.0.8 on 2020-07-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cif', '0009_auto_20200728_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='homeaddress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
