# Generated by Django 3.0.8 on 2020-07-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cif', '0010_auto_20200728_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_sap_encoded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_employee',
            field=models.CharField(default='Intercast', max_length=200),
        ),
    ]
