# Generated by Django 3.0.8 on 2020-08-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cif', '0012_auto_20200804_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='cif/images/requirements/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='cif/images/requirements/'),
        ),
    ]
