# Generated by Django 3.0.8 on 2020-08-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cif', '0013_auto_20200804_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='businesstype',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
