# Generated by Django 3.0.8 on 2020-08-04 08:45

import cif.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cif', '0014_customer_businesstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=cif.models.image_upload),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=cif.models.image_upload),
        ),
    ]
