# Generated by Django 3.0.8 on 2020-08-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cif', '0015_auto_20200804_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
