# Generated by Django 3.0.8 on 2020-08-04 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cif', '0016_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
