# Generated by Django 3.0.8 on 2020-08-10 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cif', '0020_auto_20200805_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='region',
        ),
    ]
