# Generated by Django 3.1 on 2020-08-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cif', '0021_remove_city_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
